### PR TITLE
Implement spawn and launch

### PR DESCRIPTION
**Pull request by archont94**

### CODE REVIEW

**Comment by archont94** [comment]
This is very simple implementation, but allow to pass all required parameters using strings.

**Comment by archont94** [comment]
I don't have any idea, why pipeline is sad about trailing whitespaces - even when I removed them, it is still causing error in pipeline.

**Comment by dalemyers** [comment]
The CI doesn't like that lines 294 and 299 have spaces in them. Blank lines should be entirely empty. 

Other than that, looks great! Thanks! Just that minor fix and it can be merged :)

**Comment by dalemyers** [comment]
Published in version 13.2.0

**Pull request merged**
